#!/bin/bash
# Rename a set of files using a regular expression
# JGD 2010-11-18 updated
function usage {
cat << ____EOU
    Rename multiple files at once, based upon regular expression patterns
   
    Usage: $(basename $0) input_pattern output_pattern files_to_rename
   
        e.g. $(basename $0) bread toast *bread_recipe.txt
   
    would rename 'good_bread_recipe.txt' -> 'good_toast_recipe.txt'
    et c.
     
____EOU
}

if [ $# -eq 1 ] && ([ "$1" = "-h" ] || [ "$1" = "--help" ]); then
	usage
	exit 0
elif [ $# -lt  3 ]; then
	usage
	exit 1
fi
INPUT_PATTERN=$1
OUTPUT_PATTERN=$2
shift 2
declare -a FILES
FILES=( `ls ${@}` )
for FILE in ${FILES[@]}
do
	NEWNAME=`echo $FILE | sed -e "s/${INPUT_PATTERN}/${OUTPUT_PATTERN}/"`
	echo "Renaming $FILE to $NEWNAME" >&2
	mv $FILE $NEWNAME
done
